# Version de Docker compose 
version: '3'

# Define el nombre de la red
networks: 
    laravel:

# Imagenes utilizadas para la aplicacion        
services:
    nginx:
        image: nginx:stable-alpine
        container_name: nginx
        ports: 
            # Mapeamos el puerto de la Pc con la del contenedor
            - "8080:80"
        volumes: 
            # Copiamos los archivos de nuestro proyecto a los contenedores
            - ./src:/var/www
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            # Estos contenedores deben ejecutarse antes que el que estamos declarando 
            - php
            - mysql
        networks: 
            # Definimos en que red estara 
            - laravel
    mysql:
        image: mysql:5.7.22
        container_name: mysql
        restart: unless-stopped
        tty: true
        ports: 
            - "3306:3306"
        environment: 
            MYSQL_DATABASE: laravel
            MYSQL_USER: root
            MYSQL_PASSWORD:
            MYSQL_ROOT_PASSWORD:
            SERVICE_TAGS: dev
            SERVICE_NAME: mysql
        networks: 
            - laravel
    php:
        # Indicamos que NO se generara desde una imagen
        build: 
            # Ruta
            context: .
            # Nombre del archivo
            dockerfile: Dockerfile
        # Nombre del contenedor
        container_name: php            
        volumes: 
            # Copiamos todo lo de src (Laravel) al contenedor
            - ./src:var/www            
        ports: 
            # Mapeamos los puertos
            - "9000:9000"
        networks: 
            - laravel